name: country_code_picker_plus
description: "CountryCodePickerPlus is a Flutter package that simplifies the process of capturing phone numbers with country codes."
version: 0.1.0
homepage: https://github.com/mthuong/CountryCodePickerPlus
issue_tracker: https://github.com/mthuong/CountryCodePickerPlus/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  libphonenumber_plugin:

  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - country-code-picker
  - country-code-selector
  - phone-number-input-field
  - dialing-code

screenshots:
  - description: A package that provides an easy-to-use widget for picking country codes
    path: screenshot/example_country_code_picker.gif
  - description: This widget allows users to enter a phone number with a country code
    path: screenshot/example_phone_input_field.gif
  - description: Shows the country picker in a bottom sheet
    path: screenshot/ss_bottom_sheet.png
  - description: Shows the country picker in a modal dialog
    path: screenshot/ss_dialog.png
  - description: Shows the country picker as a dropdown menu
    path: screenshot/ss_dropdown.png

flutter:
  uses-material-design: true

  assets:
    - assets/countries.json
    - assets/flags/
    - assets/circle-flags/
